name: Deployment

on:
  push:
    branches: [main]

permissions:
  pages: write
  id-token: write

concurrency:
  group: deployment
  cancel-in-progress: true

jobs:
  deployment:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: typst-community/setup-typst@v3
      - run: |
          curl -Lf https://github.com/orioncactus/pretendard/releases/download/v1.3.9/Pretendard-1.3.9.zip --output Pretendard.zip;
          unzip Pretendard.zip public/static/*.otf;
          mkdir fonts;
          cp -r public/static fonts/PretendardVariable;
      - run: ./scripts/src/compile.ts
        env:
          GH_TOKEN: ${{ github.token }}
      - run: mkdir www; typst compile --font-path fonts resume.typ www/index.pdf
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: www
      - uses: actions/deploy-pages@v4
